import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { auth } from './firebase';
import { 
  Sparkles, 
  ChevronDown, 
  BookOpen, 
  FileText, 
  Search, 
  CheckCircle2, 
  X, 
  Eye, 
  ShieldCheck, 
  Building2, 
  GraduationCap, 
  Layers,
  Info,
  Globe
} from 'lucide-react';
import './CourseModal.css';
import { API_BASE_URL } from './config';

const difficultyMap = { 'Beginner': 'BEGINNER', 'Intermediate': 'INTERMEDIATE', 'Advanced': 'ADVANCED' };

const CourseModal = ({ isOpen, onClose }) => {
  const [topic, setTopic] = useState('');
  const [difficulty, setDifficulty] = useState('Beginner');
  const [chapters, setChapters] = useState(5);
  const [includeYoutube, setIncludeYoutube] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [adaptiveLevel, setAdaptiveLevel] = useState(null);
  const [currentStage, setCurrentStage] = useState(0);
  const [currentTipIdx, setCurrentTipIdx] = useState(0);

  // Phase 3 Grounding States
  const [groundingMode, setGroundingMode] = useState('AI_ONLY'); // 'AI_ONLY' | 'INSTITUTIONAL' | 'ACADEMIC_DATABASES'
  const [institutionalCourses, setInstitutionalCourses] = useState([]);
  const [courseSearch, setCourseSearch] = useState('');
  const [selectedCourse, setSelectedCourse] = useState(null);
  const [materialsData, setMaterialsData] = useState({ course: null, materials: [] });
  const [selectedMaterialIds, setSelectedMaterialIds] = useState([]);
  const [loadingCourses, setLoadingCourses] = useState(false);
  const [loadingMaterials, setLoadingMaterials] = useState(false);
  const [enableAcademicValidation, setEnableAcademicValidation] = useState(true);

  // Material Preview Modal State
  const [previewMaterial, setPreviewMaterial] = useState(null);
  const [loadingPreview, setLoadingPreview] = useState(false);

  const navigate = useNavigate();

  const stages = [
    "🧠 Structuring adaptive syllabus outline...",
    "📚 Retrieving lecturer-approved institutional reference chunks...",
    "🔍 Scraping real-time context via Tavily search...",
    "🎥 Curating educational video tutorials from YouTube...",
    "✍️ Synthesizing detailed, textbook-quality materials...",
    "📝 Drafting custom diagnostic multiple-choice quizzes...",
    "📂 Saving curriculum & enrolling your student profile..."
  ];

  const tips = [
    "AdaptiveLearn dynamically adjusts difficulty weights based on your quiz answers and confidence ratings.",
    "Selecting lecturer-approved syllabi aligns generated chapters with official university course objectives.",
    "Every module has built-in study aids. Reviewing summaries and flashcards before a quiz can boost your score!",
    "Switch to the 'Explore' tab in the sidebar to enroll in public courses generated by other students.",
    "Did you know? You can export complete course summaries as a clean PDF document for offline learning."
  ];

  // Fetch user's adaptive level
  useEffect(() => {
    if (!isOpen || !auth.currentUser) return;
    fetch(`${API_BASE_URL}/users/${auth.currentUser.uid}`)
      .then((r) => r.json())
      .then((data) => {
        if (data.cognitiveState) {
          const level = data.cognitiveState === 'BEGINNER' ? 'Beginner'
            : data.cognitiveState === 'INTERMEDIATE' ? 'Intermediate' : 'Advanced';
          setAdaptiveLevel(level);
          setDifficulty(level);
        }
      })
      .catch(() => {});
  }, [isOpen]);

  // Fetch Institutional Courses when Institutional Grounding is selected
  useEffect(() => {
    if (!isOpen || groundingMode !== 'INSTITUTIONAL') return;
    const fetchCourses = async () => {
      setLoadingCourses(true);
      try {
        const userId = auth.currentUser?.uid || '';
        const res = await fetch(`${API_BASE_URL}/courses/institutional-courses?userId=${userId}&search=${encodeURIComponent(courseSearch)}`);
        if (res.ok) {
          const data = await res.json();
          setInstitutionalCourses(data);
        }
      } catch (err) {
        console.error('Failed to fetch institutional courses', err);
      } finally {
        setLoadingCourses(false);
      }
    };
    fetchCourses();
  }, [isOpen, groundingMode, courseSearch]);

  // Fetch Materials when an Institutional Course is selected
  useEffect(() => {
    if (!selectedCourse) {
      setMaterialsData({ course: null, materials: [] });
      setSelectedMaterialIds([]);
      return;
    }

    const fetchMaterials = async () => {
      setLoadingMaterials(true);
      try {
        const userId = auth.currentUser?.uid || '';
        const res = await fetch(`${API_BASE_URL}/courses/institutional-courses/${selectedCourse.id}/materials?userId=${userId}`);
        if (res.ok) {
          const data = await res.json();
          setMaterialsData(data);
          // Default select all available materials for the selected course
          if (data.materials) {
            setSelectedMaterialIds(data.materials.map((m) => m.id));
          }
        }
      } catch (err) {
        console.error('Failed to fetch course materials', err);
      } finally {
        setLoadingMaterials(false);
      }
    };
    fetchMaterials();
  }, [selectedCourse]);

  // Stage & tip rotation timers
  useEffect(() => {
    let stageInterval;
    let tipInterval;

    if (isGenerating) {
      setCurrentStage(0);
      setCurrentTipIdx(Math.floor(Math.random() * tips.length));

      stageInterval = setInterval(() => {
        setCurrentStage((prev) => (prev < stages.length - 1 ? prev + 1 : prev));
      }, 3500);

      tipInterval = setInterval(() => {
        setCurrentTipIdx((prev) => (prev + 1) % tips.length);
      }, 5000);
    }

    return () => {
      clearInterval(stageInterval);
      clearInterval(tipInterval);
    };
  }, [isGenerating]);

  if (!isOpen) return null;

  const handleSelectAll = () => {
    if (materialsData.materials) {
      setSelectedMaterialIds(materialsData.materials.map((m) => m.id));
    }
  };

  const handleClearSelection = () => {
    setSelectedMaterialIds([]);
  };

  const toggleMaterialCheck = (id) => {
    setSelectedMaterialIds((prev) =>
      prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]
    );
  };

  const handleInspectPreview = async (materialId) => {
    setLoadingPreview(true);
    try {
      const userId = auth.currentUser?.uid || '';
      const res = await fetch(`${API_BASE_URL}/courses/materials/${materialId}/preview?userId=${userId}`);
      if (res.ok) {
        const data = await res.json();
        setPreviewMaterial(data);
      }
    } catch (err) {
      console.error('Failed to fetch preview', err);
    } finally {
      setLoadingPreview(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!topic || isGenerating) return;

    if (groundingMode === 'INSTITUTIONAL' && !selectedCourse) {
      alert('Please select an institutional course to ground your AI course.');
      return;
    }

    setIsGenerating(true);
    try {
      const effectiveGroundingMode = (groundingMode === 'INSTITUTIONAL' && enableAcademicValidation) ? 'HYBRID' : groundingMode;

      const res = await fetch(`${API_BASE_URL}/courses/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userId: auth.currentUser ? auth.currentUser.uid : 'temp-user-id',
          topic,
          difficulty: difficultyMap[difficulty] || 'BEGINNER',
          chapters,
          includeYoutube,
          groundingMode: effectiveGroundingMode,
          academicCourseId: selectedCourse ? selectedCourse.id : undefined,
          academicMaterialIds: (groundingMode === 'INSTITUTIONAL' || effectiveGroundingMode === 'HYBRID') ? selectedMaterialIds : [],
        }),
      });
      const data = await res.json();

      if (data.success) {
        onClose();
        navigate(`/course/${data.courseId}`);
      } else {
        alert(data.message || 'Generation failed');
      }
    } catch (err) {
      console.error(err);
      alert('Error generating course. Is the backend running?');
    } finally {
      setIsGenerating(false);
    }
  };

  const syllabusMaterial = materialsData.materials.find((m) => m.isSyllabusOrOutline);
  const otherMaterials = materialsData.materials.filter((m) => !m.isSyllabusOrOutline);

  return (
    <div className="modal-overlay" onClick={isGenerating ? undefined : onClose}>
      <div className="modal-container" style={{ maxWidth: 640 }} onClick={(e) => e.stopPropagation()}>
        {!isGenerating && <button className="modal-close" onClick={onClose}>✕</button>}

        {isGenerating ? (
          <div className="generator-loading-wrapper">
            <div className="glowing-spinner-wrap">
              <div className="glowing-spinner"></div>
              <Sparkles className="glowing-icon" size={26} />
            </div>
            <h2 className="loading-title">Crafting Grounded Course</h2>
            <p className="loading-subtitle">
              Building a curriculum for <span>"{topic}"</span>
            </p>

            <div className="loading-stages">
              {stages.map((stage, idx) => {
                let statusClass = "pending";
                if (currentStage > idx) statusClass = "completed";
                else if (currentStage === idx) statusClass = "active";

                return (
                  <div key={idx} className={`loading-stage ${statusClass}`}>
                    <div className="stage-indicator">
                      {statusClass === "completed" ? (
                        <span className="stage-check">✓</span>
                      ) : statusClass === "active" ? (
                        <span className="stage-dot-pulse"></span>
                      ) : (
                        <span className="stage-dot-pending"></span>
                      )}
                    </div>
                    <span className="stage-label">{stage}</span>
                  </div>
                );
              })}
            </div>

            <div className="loading-tips-carousel">
              <div className="tip-card">
                <span className="tip-badge">CURRICULUM ALIGNMENT</span>
                <p className="tip-text">{tips[currentTipIdx]}</p>
              </div>
            </div>
          </div>
        ) : (
          <>
            <div className="modal-header">
              <h2 className="modal-title">Create an AI Course</h2>
              <p className="modal-subtitle">Specify your learning topic, difficulty, and academic grounding preferences.</p>
            </div>

            <form className="modal-form" onSubmit={handleSubmit}>
              {/* Field 1: Topic */}
              <div className="form-group">
                <label>WHAT DO YOU WANT TO LEARN?</label>
                <input
                  type="text"
                  placeholder="e.g. Research Methods in Information Technology, Operating Systems"
                  className="form-input"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  required
                  autoFocus
                />
              </div>

              {/* Field 2: Difficulty & Chapters */}
              <div className="form-row">
                <div className="form-group">
                  <label>
                    DIFFICULTY
                    {adaptiveLevel && (
                      <span className="adaptive-hint">Your level: {adaptiveLevel}</span>
                    )}
                  </label>
                  <div className="select-wrapper">
                    <select className="form-select" value={difficulty} onChange={(e) => setDifficulty(e.target.value)}>
                      <option value="Beginner">Beginner</option>
                      <option value="Intermediate">Intermediate</option>
                      <option value="Advanced">Advanced</option>
                    </select>
                    <ChevronDown size={16} className="select-icon" />
                  </div>
                </div>

                <div className="form-group">
                  <label>NUMBER OF CHAPTERS</label>
                  <input
                    type="number"
                    min={1}
                    max={20}
                    className="form-input"
                    value={chapters}
                    onChange={(e) => setChapters(Math.min(20, Math.max(1, Number(e.target.value))))}
                    style={{ width: '100%', height: '42px', boxSizing: 'border-box' }}
                  />
                </div>
              </div>

              {/* Field 3: Academic Grounding Section */}
              <div className="grounding-section">
                <div className="grounding-title-row">
                  <div className="grounding-heading">
                    <ShieldCheck size={18} style={{ color: '#818cf8' }} /> ACADEMIC GROUNDING
                  </div>
                  <div className="grounding-subtext">
                    Ground your AI-generated course using lecturer-approved institutional academic materials.
                  </div>
                </div>

                <div className="grounding-options-grid">
                  {/* Option A: AI Knowledge Only */}
                  <label 
                    className={`grounding-option-card ${groundingMode === 'AI_ONLY' ? 'selected' : ''}`}
                    onClick={() => setGroundingMode('AI_ONLY')}
                  >
                    <input
                      type="radio"
                      name="groundingMode"
                      checked={groundingMode === 'AI_ONLY'}
                      onChange={() => setGroundingMode('AI_ONLY')}
                      className="grounding-radio"
                    />
                    <div className="grounding-option-info">
                      <span className="grounding-option-title">⚡ AI Knowledge Only</span>
                      <span className="grounding-option-desc">Generates course content using general LLM web synthesis and Tavily facts.</span>
                    </div>
                  </label>

                  {/* Option B: Institutional Academic Materials */}
                  <label 
                    className={`grounding-option-card ${groundingMode === 'INSTITUTIONAL' ? 'selected' : ''}`}
                    onClick={() => setGroundingMode('INSTITUTIONAL')}
                  >
                    <input
                      type="radio"
                      name="groundingMode"
                      checked={groundingMode === 'INSTITUTIONAL'}
                      onChange={() => setGroundingMode('INSTITUTIONAL')}
                      className="grounding-radio"
                    />
                    <div className="grounding-option-info">
                      <span className="grounding-option-title" style={{ color: '#34d399' }}>
                        🎓 Institutional Academic Materials
                      </span>
                      <span className="grounding-option-desc">
                        Aligns generated topics with official department syllabi, course outlines, and lecture notes.
                      </span>
                    </div>
                  </label>

                  {/* Option C: External Academic Database (OpenAlex API) */}
                  <label
                    className={`grounding-option-card ${groundingMode === 'EXTERNAL' ? 'selected' : ''}`}
                    onClick={() => setGroundingMode('EXTERNAL')}
                    style={{ cursor: 'pointer' }}
                  >
                    <input
                      type="radio"
                      name="groundingMode"
                      checked={groundingMode === 'EXTERNAL'}
                      onChange={() => setGroundingMode('EXTERNAL')}
                      className="grounding-radio"
                    />
                    <div className="grounding-option-info">
                      <span className="grounding-option-title" style={{ color: '#60a5fa' }}>
                        🌐 External Academic Database (OpenAlex API)
                      </span>
                      <span className="grounding-option-desc">
                        Grounds generated topics with peer-reviewed scholarly publications, DOIs, and academic citations via OpenAlex.
                      </span>
                    </div>
                  </label>
                </div>

                {/* Sub-Section: External OpenAlex Card */}
                {groundingMode === 'EXTERNAL' && (
                  <div className="course-selector-box" style={{ marginTop: 8, background: 'rgba(59, 130, 246, 0.08)', border: '1px solid rgba(59, 130, 246, 0.3)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                      <Globe size={18} style={{ color: '#60a5fa' }} />
                      <span style={{ fontSize: '0.88rem', fontWeight: 700, color: 'white' }}>
                        Connected to OpenAlex Global Research Database
                      </span>
                    </div>
                    <p style={{ fontSize: '0.82rem', color: '#cbd5e1', margin: 0, lineHeight: 1.4 }}>
                      OpenAlex API will automatically query over 250 million global research papers, retrieving top peer-reviewed articles, author attributions, citation counts, and DOIs for your topic.
                    </p>
                  </div>
                )}

                {/* Sub-Section: Institutional Course & Material Selection */}
                {groundingMode === 'INSTITUTIONAL' && (
                  <div className="course-selector-box" style={{ marginTop: 8 }}>
                    <label style={{ fontSize: '0.82rem', fontWeight: 700, color: '#818cf8', textTransform: 'uppercase' }}>
                      SELECT INSTITUTIONAL COURSE
                    </label>

                    {/* Search Input */}
                    <div style={{ position: 'relative' }}>
                      <Search size={16} style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', color: '#64748b' }} />
                      <input
                        type="text"
                        placeholder="Search course title or code (e.g. IT 401, Research Methods)..."
                        value={courseSearch}
                        onChange={(e) => setCourseSearch(e.target.value)}
                        className="form-input"
                        style={{ paddingLeft: 36, fontSize: '0.88rem' }}
                      />
                    </div>

                    {/* Course Selection Dropdown / Cards */}
                    {institutionalCourses.length > 0 ? (
                      <div style={{ maxHeight: 160, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 6 }}>
                        {institutionalCourses.map((c) => (
                          <div
                            key={c.id}
                            onClick={() => setSelectedCourse(c)}
                            style={{
                              padding: '10px 12px',
                              borderRadius: 8,
                              background: selectedCourse?.id === c.id ? 'rgba(99, 102, 241, 0.2)' : 'rgba(255,255,255,0.03)',
                              border: selectedCourse?.id === c.id ? '1px solid #6366f1' : '1px solid rgba(255,255,255,0.06)',
                              cursor: 'pointer',
                              display: 'flex',
                              justify: 'space-between',
                              alignItems: 'center',
                            }}
                          >
                            <div>
                              <div style={{ fontSize: '0.88rem', fontWeight: 700, color: 'white' }}>
                                <span style={{ color: '#818cf8', marginRight: 6 }}>[{c.code}]</span> {c.title}
                              </div>
                              <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
                                {c.programme} • {c.level} ({c.academicYear})
                              </div>
                            </div>
                            <span style={{ fontSize: '0.72rem', color: '#34d399', fontWeight: 600 }}>
                              {c.availableMaterialCount} Materials
                            </span>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <div style={{ fontSize: '0.82rem', color: '#64748b', textAlign: 'center', padding: '12px 0' }}>
                        {loadingCourses ? 'Loading active institutional courses...' : 'No published institutional courses found.'}
                      </div>
                    )}

                    {/* Selected Course Metadata Header */}
                    {selectedCourse && (
                      <div className="selected-course-card">
                        <div style={{ fontSize: '0.9rem', fontWeight: 800, color: 'white', marginBottom: 4 }}>
                          {selectedCourse.code}: {selectedCourse.title}
                        </div>
                        <div style={{ fontSize: '0.8rem', color: '#cbd5e1', lineHeight: 1.4 }}>
                          Institution: {selectedCourse.institution} • {selectedCourse.programme} ({selectedCourse.level})<br />
                          Lecturer: {typeof selectedCourse.lecturer === 'string' ? selectedCourse.lecturer : (selectedCourse.lecturer?.name || selectedCourse.lecturerName || 'Dr. Lecturer')}
                        </div>
                      </div>
                    )}

                    {/* Multi-Material Checklist */}
                    {selectedCourse && materialsData.materials.length > 0 && (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginTop: 6 }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                          <span style={{ fontSize: '0.8rem', fontWeight: 700, color: 'white', textTransform: 'uppercase' }}>
                            SELECT ACADEMIC REFERENCES ({selectedMaterialIds.length} selected)
                          </span>

                          <div style={{ display: 'flex', gap: 8 }}>
                            <button
                              type="button"
                              onClick={handleSelectAll}
                              style={{ background: 'transparent', border: 'none', color: '#818cf8', fontSize: '0.75rem', fontWeight: 700, cursor: 'pointer' }}
                            >
                              Select All
                            </button>
                            <span style={{ color: '#64748b' }}>|</span>
                            <button
                              type="button"
                              onClick={handleClearSelection}
                              style={{ background: 'transparent', border: 'none', color: '#f87171', fontSize: '0.75rem', fontWeight: 700, cursor: 'pointer' }}
                            >
                              Clear
                            </button>
                          </div>
                        </div>

                        {/* Highlighted Syllabus Card */}
                        {syllabusMaterial && (
                          <div className="recommended-syllabus-card">
                            <input
                              type="checkbox"
                              checked={selectedMaterialIds.includes(syllabusMaterial.id)}
                              onChange={() => toggleMaterialCheck(syllabusMaterial.id)}
                              className="material-checkbox"
                              style={{ marginTop: 2 }}
                            />
                            <div style={{ flex: 1 }}>
                              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                                <span className="recommended-badge">RECOMMENDED CURRICULUM REFERENCE</span>
                                <span style={{ fontSize: '0.72rem', color: '#94a3b8' }}>Syllabus</span>
                              </div>
                              <div style={{ fontSize: '0.88rem', fontWeight: 700, color: 'white' }}>
                                {syllabusMaterial.title}
                              </div>
                              <div style={{ fontSize: '0.78rem', color: '#cbd5e1', marginTop: 2 }}>
                                Using this syllabus helps AdaptiveLearn structure the generated course around the lecturer-defined course objectives and topics.
                              </div>
                            </div>
                            <button
                              type="button"
                              onClick={() => handleInspectPreview(syllabusMaterial.id)}
                              className="preview-btn"
                            >
                              <Eye size={14} /> Preview
                            </button>
                          </div>
                        )}

                        {/* Other Lecture Notes & Materials Checklist */}
                        <div className="materials-checklist">
                          {otherMaterials.map((mat) => (
                            <div 
                              key={mat.id} 
                              className={`material-check-item ${selectedMaterialIds.includes(mat.id) ? 'selected' : ''}`}
                            >
                              <div className="material-check-left">
                                <input
                                  type="checkbox"
                                  checked={selectedMaterialIds.includes(mat.id)}
                                  onChange={() => toggleMaterialCheck(mat.id)}
                                  className="material-checkbox"
                                />
                                <div>
                                  <div style={{ fontSize: '0.85rem', fontWeight: 600, color: 'white' }}>{mat.title}</div>
                                  <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
                                    {mat.materialType.replace('_', ' ')} • {mat.wordCount} words
                                  </div>
                                </div>
                              </div>

                              <button
                                type="button"
                                onClick={() => handleInspectPreview(mat.id)}
                                className="preview-btn"
                              >
                                <Eye size={13} /> Preview
                              </button>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Academic Database Validation Toggle */}
                    <div 
                      onClick={() => setEnableAcademicValidation(!enableAcademicValidation)}
                      style={{
                        marginTop: 12,
                        padding: '12px 14px',
                        background: enableAcademicValidation ? 'rgba(59, 130, 246, 0.12)' : 'rgba(255, 255, 255, 0.03)',
                        border: enableAcademicValidation ? '1px solid rgba(59, 130, 246, 0.35)' : '1px solid rgba(255, 255, 255, 0.08)',
                        borderRadius: 10,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        cursor: 'pointer',
                        transition: 'all 0.2s ease'
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                        <Globe size={18} style={{ color: enableAcademicValidation ? '#60a5fa' : '#94a3b8' }} />
                        <div>
                          <div style={{ fontSize: '0.86rem', fontWeight: 700, color: 'white', display: 'flex', alignItems: 'center', gap: 6 }}>
                            Cross-Validate with Academic Research Database (OpenAlex)
                            {enableAcademicValidation && (
                              <span style={{ fontSize: '0.7rem', padding: '1px 6px', borderRadius: 4, background: 'rgba(59, 130, 246, 0.2)', color: '#60a5fa', fontWeight: 800 }}>HYBRID MODE ACTIVE</span>
                            )}
                          </div>
                          <div style={{ fontSize: '0.78rem', color: '#94a3b8', marginTop: 2, lineHeight: 1.3 }}>
                            Cross-validates lecture notes with 250M+ peer-reviewed papers, scholarly citations & DOIs from OpenAlex.
                          </div>
                        </div>
                      </div>
                      <div className="toggle-switch" style={{ marginLeft: 12 }}>
                        <input 
                          type="checkbox" 
                          checked={enableAcademicValidation} 
                          onChange={(e) => setEnableAcademicValidation(e.target.checked)} 
                        />
                        <span className="toggle-slider"></span>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Field 4: YouTube Videos Toggle */}
              <div className="form-group">
                <label className="toggle-container">
                  <div className="toggle-label">
                    <span className="toggle-icon">▶</span>
                    <span>Include YouTube Video Tutorials</span>
                  </div>
                  <div className="toggle-switch">
                    <input type="checkbox" checked={includeYoutube} onChange={(e) => setIncludeYoutube(e.target.checked)} />
                    <span className="toggle-slider"></span>
                  </div>
                </label>
              </div>

              {/* Form Actions */}
              <div className="modal-actions">
                <button type="button" className="btn btn-ghost" onClick={onClose} disabled={isGenerating}>
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary" disabled={isGenerating || !topic}>
                  <Sparkles size={15} /> {isGenerating ? "Generating..." : "Generate Course"}
                </button>
              </div>
            </form>
          </>
        )}
      </div>

      {/* Material Preview Dialog Modal */}
      {previewMaterial && (
        <div className="modal-overlay" onClick={() => setPreviewMaterial(null)} style={{ zIndex: 1100 }}>
          <div className="modal-container" style={{ maxWidth: 580 }} onClick={(e) => e.stopPropagation()}>
            <div className="modal-header" style={{ marginBottom: 16 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span className="coming-soon-badge" style={{ background: 'rgba(99, 102, 241, 0.2)', color: '#818cf8' }}>
                  {previewMaterial.materialType}
                </span>
                <button className="close-btn" onClick={() => setPreviewMaterial(null)}>
                  <X size={18} />
                </button>
              </div>
              <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: 'white', marginTop: 8 }}>{previewMaterial.title}</h3>
              <p style={{ fontSize: '0.82rem', color: '#94a3b8', margin: 0 }}>
                Course: {previewMaterial.courseTitle} • Uploader: {previewMaterial.lecturerName}
              </p>
            </div>

            {previewMaterial.syllabusStructure ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 14, maxHeight: 400, overflowY: 'auto' }}>
                {previewMaterial.syllabusStructure.objectives?.length > 0 && (
                  <div>
                    <h4 style={{ fontSize: '0.8rem', color: '#818cf8', fontWeight: 700, marginBottom: 6 }}>COURSE OBJECTIVES</h4>
                    <ul style={{ paddingLeft: 18, color: '#cbd5e1', fontSize: '0.85rem', margin: 0 }}>
                      {previewMaterial.syllabusStructure.objectives.map((o, idx) => (
                        <li key={idx}>{o}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {previewMaterial.syllabusStructure.topics?.length > 0 && (
                  <div>
                    <h4 style={{ fontSize: '0.8rem', color: '#34d399', fontWeight: 700, marginBottom: 6 }}>WEEKLY TOPICS</h4>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                      {previewMaterial.syllabusStructure.topics.map((t, idx) => (
                        <div key={idx} style={{ fontSize: '0.82rem', color: '#e2e8f0', background: 'rgba(255,255,255,0.03)', padding: '6px 10px', borderRadius: 6 }}>
                          <span style={{ color: '#818cf8', fontWeight: 700 }}>Week {t.weekNumber || idx + 1}:</span> {t.title}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div style={{
                background: 'rgba(15, 23, 42, 0.6)',
                border: '1px solid rgba(255, 255, 255, 0.08)',
                borderRadius: 10,
                padding: 16,
                fontSize: '0.85rem',
                color: '#cbd5e1',
                maxHeight: 350,
                overflowY: 'auto',
                whiteSpace: 'pre-wrap',
                fontFamily: 'monospace',
              }}>
                {previewMaterial.previewSnippet || 'No preview available.'}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default CourseModal;
