import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { auth } from './firebase';
import { Sparkles, ArrowRight, ChevronDown } from 'lucide-react';
import './CourseModal.css';
import { API_BASE_URL } from './config';

const difficultyMap = { 'Beginner': 'BEGINNER', 'Intermediate': 'INTERMEDIATE', 'Advanced': 'ADVANCED' };

const CourseModal = ({ isOpen, onClose }) => {
  const [topic, setTopic] = useState("");
  const [difficulty, setDifficulty] = useState("Beginner");
  const [chapters, setChapters] = useState(5);
  const [includeYoutube, setIncludeYoutube] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [adaptiveLevel, setAdaptiveLevel] = useState(null);
  const [currentStage, setCurrentStage] = useState(0);
  const [currentTipIdx, setCurrentTipIdx] = useState(0);
  const navigate = useNavigate();

  const stages = [
    "🧠 Structuring adaptive syllabus outline...",
    "🔍 Scraping real-time context via Tavily search...",
    "🎥 Curating educational video tutorials from YouTube...",
    "✍️ Synthesizing detailed, textbook-quality materials...",
    "📝 Drafting custom diagnostic multiple-choice quizzes...",
    "🗃️ Designing flashcards and practical study tasks...",
    "📂 Saving curriculum & enrolling your student profile..."
  ];

  const tips = [
    "AdaptiveLearn dynamically adjusts difficulty weights based on your quiz answers and confidence ratings.",
    "If you find a chapter easy, the cognitive engine automatically transitions you to intermediate or advanced modules.",
    "Every module has built-in study aids. Reviewing summaries and flashcards before a quiz can boost your score!",
    "Switch to the 'Explore' tab in the sidebar to enroll in public courses generated by other students.",
    "Did you know? You can export complete course summaries as a clean PDF document for offline learning."
  ];

  // Fetch user's adaptive level and pre-fill difficulty
  useEffect(() => {
    if (!isOpen || !auth.currentUser) return;
    fetch(`${API_BASE_URL}/users/${auth.currentUser.uid}`)
      .then(r => r.json())
      .then(data => {
        if (data.cognitiveState) {
          const level = data.cognitiveState === 'BEGINNER' ? 'Beginner'
            : data.cognitiveState === 'INTERMEDIATE' ? 'Intermediate' : 'Advanced';
          setAdaptiveLevel(level);
          setDifficulty(level);
        }
      })
      .catch(() => {});
  }, [isOpen]);

  useEffect(() => {
    let stageInterval;
    let tipInterval;

    if (isGenerating) {
      setCurrentStage(0);
      setCurrentTipIdx(Math.floor(Math.random() * tips.length));

      // Advance stages dynamically
      stageInterval = setInterval(() => {
        setCurrentStage((prev) => {
          if (prev < stages.length - 1) {
            return prev + 1;
          }
          return prev;
        });
      }, 3500);

      // Rotate tips
      tipInterval = setInterval(() => {
        setCurrentTipIdx((prev) => (prev + 1) % tips.length);
      }, 5000);
    }

    return () => {
      clearInterval(stageInterval);
      clearInterval(tipInterval);
    };
  }, [isGenerating]);

  if (!isOpen) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!topic || isGenerating) return;

    setIsGenerating(true);
    try {
      const res = await fetch(`${API_BASE_URL}/courses/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userId: auth.currentUser ? auth.currentUser.uid : 'temp-user-id',
          topic,
          difficulty: difficultyMap[difficulty] || 'BEGINNER',
          chapters,
          includeYoutube
        })
      });
      const data = await res.json();

      if (data.success) {
        onClose();
        navigate(`/course/${data.courseId}`);
      } else {
        alert(data.message || "Generation failed");
      }
    } catch (err) {
      console.error(err);
      alert("Error generating course. Is the backend running?");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="modal-overlay" onClick={isGenerating ? undefined : onClose}>
      <div className="modal-container" onClick={(e) => e.stopPropagation()}>
        {!isGenerating && <button className="modal-close" onClick={onClose}>✕</button>}

        {isGenerating ? (
          <div className="generator-loading-wrapper">
            <div className="glowing-spinner-wrap">
              <div className="glowing-spinner"></div>
              <Sparkles className="glowing-icon" size={26} />
            </div>
            <h2 className="loading-title">Crafting Your Course</h2>
            <p className="loading-subtitle">
              Building a personalized curriculum for <span>"{topic}"</span>
            </p>

            <div className="loading-stages">
              {stages.map((stage, idx) => {
                let statusClass = "pending";
                if (currentStage > idx) statusClass = "completed";
                else if (currentStage === idx) statusClass = "active";

                return (
                  <div key={idx} className={`loading-stage ${statusClass}`}>
                    <div className="stage-indicator">
                      {statusClass === "completed" ? (
                        <span className="stage-check">✓</span>
                      ) : statusClass === "active" ? (
                        <span className="stage-dot-pulse"></span>
                      ) : (
                        <span className="stage-dot-pending"></span>
                      )}
                    </div>
                    <span className="stage-label">{stage}</span>
                  </div>
                );
              })}
            </div>

            <div className="loading-tips-carousel">
              <div className="tip-card">
                <span className="tip-badge">DID YOU KNOW?</span>
                <p className="tip-text">{tips[currentTipIdx]}</p>
              </div>
            </div>
          </div>
        ) : (
          <>
            <div className="modal-header">
              <h2 className="modal-title">Create a course</h2>
              <p className="modal-subtitle">Tell us what you want to learn and we'll build it for you.</p>
            </div>

            <form className="modal-form" onSubmit={handleSubmit}>
              <div className="form-group">
                <label>What do you want to learn?</label>
                <input
                  type="text"
                  placeholder="e.g. Machine Learning, Spanish, Photography"
                  className="form-input"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  required
                  autoFocus
                />
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>
                    Difficulty
                    {adaptiveLevel && (
                      <span className="adaptive-hint">Your level: {adaptiveLevel}</span>
                    )}
                  </label>
                  <div className="select-wrapper">
                    <select className="form-select" value={difficulty} onChange={e => setDifficulty(e.target.value)}>
                      <option value="Beginner">Beginner</option>
                      <option value="Intermediate">Intermediate</option>
                      <option value="Advanced">Advanced</option>
                    </select>
                    <ChevronDown size={16} className="select-icon" />
                  </div>
                </div>

                <div className="form-group">
                  <label>Chapters</label>
                  <input
                    type="number"
                    min={1}
                    max={20}
                    className="form-input"
                    value={chapters}
                    onChange={e => setChapters(Math.min(20, Math.max(1, Number(e.target.value))))}
                    style={{ width: '100%', height: '42px', boxSizing: 'border-box' }}
                  />
                </div>
              </div>

              <div className="form-group">
                <label className="toggle-container">
                  <div className="toggle-label">
                    <span className="toggle-icon">▶</span>
                    <span>Include YouTube videos</span>
                  </div>
                  <div className="toggle-switch">
                    <input type="checkbox" checked={includeYoutube} onChange={e => setIncludeYoutube(e.target.checked)} />
                    <span className="toggle-slider"></span>
                  </div>
                </label>
              </div>

              <div className="modal-actions">
                <button type="button" className="btn btn-ghost" onClick={onClose} disabled={isGenerating}>
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary" disabled={isGenerating || !topic}>
                  <Sparkles size={15} /> {isGenerating ? "Generating..." : "Generate Course"}
                </button>
              </div>
            </form>
          </>
        )}
      </div>
    </div>
  );
};

export default CourseModal;
